HONK:
    decimalPlace:
        - 5
    updateFreq: 60
    discordBotKey:
    guildId:
kekleo:
    decimalPlace:
        - 5
    updateFreq: 60
    discordBotKey:
    guildId:
ROPE:
    decimalPlace:
        - 5
    updateFreq: 60
    discordBotKey:
    guildId:
Argyl:
    decimalPlace:
        - 5
    updateFreq: 60
    discordBotKey:
    guildId:
