SAUCEINU:
    decimalPlace:
        - 9
    updateFreq: 10
    discordBotKey: xx
    guildId:
        - xx
        - xx
token:
    decimalPlace:
        - 5
    updateFreq: 60
    discordBotKey: xxx
    guildId:
        - xxx
        - xxx

