SAUCEINU:
    decimalPlace:
        - 9
    updateFreq: 10
    discordBotKey: MTA4Njg0NjkzNTk0NTcxNTc3NA.GOTHfr.zneAJOmvy4IgDXrhufmaWSqakHq4g43lS3viIA
    guildId:
        - 1126485878404026488
token:
    decimalPlace:
        - 5
    updateFreq: 60
    discordBotKey: xxx
    guildId:
        - xxx
        - xxx

